---
language: python
services: docker

install:
  - python3 -m pip install ansible-core molecule[docker] yamllint ansible-lint docker

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/